server:
  port: 8999

spring:
  application:
    name: rainbow-generator

  datasource:
    username: honyar
    password: '*honyar123456#'
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-uf670w71rw14ib5yd6o.mysql.rds.aliyuncs.com:3306/ibs?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT&allowMultiQueries=true


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.rainbow.generator.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false
